### ISSUE TITLE
Error Captcha

### ISSUE THREAD

**Issue by satrox28** [marbink/PoGo-Captcha#5]
[ INFO][user] Login OK [1 attempt(s)]
[ INFO][user] Captcha required
[DEBUG][user] CaptchaURL: https://pgorelease.nianticlabs.com/plfe/xxx/captcha/xxxxxxxxxxxx
[ERROR][user] WebDriverException()
[DEBUG][user] <class 'selenium.common.exceptions.WebDriverException'>
[DEBUG][user] 143

CMD: python PoGo-Captcha/pogo-captcha.py -ac PoGo-Captcha/accounts.csv -c xxxxxxxxxxxxxxxxxxxxxxx -v -l 1.xxxxxxx,103.xxxxxx

May I know what I am missing, I have installed required plugins.

Do I need to deposit money on 2captcha account, can i solve captcha manually through browser.

**Comment by marbink** [comment]
Did you put PhantomJS in the right place?

**Comment by satrox28** [comment]
Yes not its working after installing latest chromedriver.

If need to autosolve then need to buy on 2captcha.

Is it possible to solve Captcha command line without gui??

**Comment by marbink** [comment]
@satrox28 chromedriver and PhantomJS are two different things. I asked  you about one and you wrote about the other. Anyway, If you don't want to pay 2captcha, you can solve them manually. There's no way to do it without GUI.

**Comment by macinmn** [comment]
just curious why (since it's not the default install method) you need to install Chrome in ProgramFiles; why can't the script just call 'Chrome' and not specify that directory?   PTC2 account creation script, which also uses Chrome Driver with Selenium, works fine that way (https://github.com/Kitryn/PTCAccount2) with a standard install in user account AppData folder.  I guess I'm reluctant to go through the effort of uninstalling Chrome to reinstall it and potentially losing something along the way.

**Comment by satrox28** [comment]
@marbink sorry typo on my previous reply

Yes, its working after installing latest chromedriver. I have installed phantomjs too, tried manual captcha
